### ISSUE TITLE
Issue with update to 3.2.0.0

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#14]
I've updated my version of pandoc-numbering, using

    pip install --upgrade --force --no-cache git+https://github.com/chdemko/pandoc-numbering

and I'm currently running pandoc 2.9.2.1.

And now I can't compile a file as simple as the one from #12 : 

```bash
pandoc test.md --toc -s --filter pandoc-numbering -o test.html
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 11, in <module>
    load_entry_point('pandoc-numbering==3.2.0.0', 'console_scripts', 'pandoc-numbering')()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/caubert/.local/lib/python2.7/site-packages/pandoc_numbering.py", line 14, in <module>
    from panflute import (  # type: ignore
  File "/home/caubert/.local/lib/python2.7/site-packages/panflute/__init__.py", line 9, in <module>
    from .containers import ListContainer, DictContainer
  File "/home/caubert/.local/lib/python2.7/site-packages/panflute/containers.py", line 42
    def __init__(self, *args, oktypes=object, parent=None):
                                    ^
SyntaxError: invalid syntax
Error running filter pandoc-numbering:
Filter returned error status 1

```

**Comment by chdemko** [comment]
Can you use python3?

**Comment by chdemko** [comment]
Or you can force to use panflute 1.11

~~~console
$ pip install --force panflute==1.11.0
~~~

I will publish a fix soon

**Comment by aubertc** [comment]
> Or you can force to use panflute 1.11
> 
> ```
> $ pip install --force panflute==1.11.0
> ```

That does not seem to do the trick:

```bash
pip install --force panflute==1.11.0
…
Successfully installed future-0.18.2 panflute-1.11.0 pyyaml-5.3.1 shutilwhich-1.1.0
```

```bash
pandoc test.md --toc -s --filter pandoc-numbering -o test.html
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 11, in <module>
    load_entry_point('pandoc-numbering==3.2.0.0', 'console_scripts', 'pandoc-numbering')()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/caubert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 14, in <module>
    from panflute import (  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/panflute/__init__.py", line 9, in <module>
    from .containers import ListContainer, DictContainer
  File "/usr/local/lib/python2.7/dist-packages/panflute/containers.py", line 42
    def __init__(self, *args, oktypes=object, parent=None):
                                    ^
SyntaxError: invalid syntax
Error running filter pandoc-numbering:
Filter returned error status 1
```

**Comment by aubertc** [comment]
> Can you use python3?

I should probably do that, yes.
