### ISSUE TITLE
Dealing with tables having a header

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#23]
The following table:

```md
test | Ah !
:---: | :---: 
Pandoc | Is happy
```
is processed just fine by pandoc, but calling the `pandoc-numbering` filter returns

```
pandoc test.md --filter pandoc-numbering -o test.html
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 8, in <module>
    sys.exit(main())
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 1440, in main
    [numbering, referencing], prepare=prepare, doc=doc, finalize=finalize
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/io.py", line 233, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/io.py", line 56, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/elements.py", line 1478, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: ColWidthDefault
Error running filter pandoc-numbering:
Filter returned error status 1
```

According to panflute's developer, https://github.com/sergiocorreia/panflute/issues/76#issuecomment-729833809

> The latest versions of Pandoc and pandoc-tables revamped the Table() API, which we recently added to Panflute, so I guess the problems lies there.
>
> I'm not familiar with the internals of pandoc-numbering, but it seems that it's trying to feed the .head of a table into a numbered list, which will fail (before, the head was just a list, now it's a proper object).

I tried to locate the issue but was not succesfull.

**Comment by aubertc** [comment]
So, actually, pandoc-numbering is fine, except that it requires an outdated version of panflute. Requiring the new version of panflute fix this issue.

As a hot-fix, you can:

0. Uninstall panflute and pandoc-numbering. You can check with
        `pip list | grep pan`
what is installed, and if panflute or pandoc-numbering are installed, delete them with
   `python -m pip uninstall pandoc-numbering`
   `python -m pip uninstall panflute`
1. Download the source code of pandoc-numbering,
2. Open setup.py and replace
    `install_requires=["panflute<1.12", "pypandoc>=1.4"],`
with
    `install_requires=["panflute<2.0.5", "pypandoc>=1.4"],`
3. Install the modified version using (still in the directory where the source code is)
     `pip install .`

This should install the current version of panflute at the same time, and that bug should disappear. _Et voilà!_
