### ISSUE TITLE
Tables with pipe rendering

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#8]
If you look at [the official documentation for tables in pandoc](https://pandoc.org/MANUAL.html#tables), you can read:

> So, this is a perfectly legal (though ugly) pipe table:
>
>    fruit| price
>     -----|-----:
>     apple|2.05
>     pear|1.37
>     orange|3.09

However, using the pandoc-numbering filter breaks this syntax:

```
|
:---: | :---: 
Pandoc | Is happy
```
Using `pandoc MWE.md` yelds the expected output (a simple table), but `pandoc MWE.md --filter pandoc-numbering` causes an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 11, in <module>
    load_entry_point('pandoc-numbering==3.0.2', 'console_scripts', 'pandoc-numbering')()
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 693, in main
    return run_filters([numbering, referencing], prepare = prepare, doc = doc, finalize = finalize)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 238, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 61, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 1521, in from_json
    header=header)
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 1129, in __init__
    self.header = header
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 1165, in header
    raise IndexError(msg)
IndexError: table header has an incorrect number of cols: 1 rows but expected 2
Error running filter pandoc-numbering:
Filter returned error status 1
```

**Comment by chdemko** [comment]
Unfortunately, this error cames from the panflute library (which is used in pandoc-numbering). See https://github.com/sergiocorreia/panflute

**Comment by chdemko** [comment]
Vous travaillez pour le CNRS ? :)

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/76

**Comment by aubertc** [comment]
Ok, so apparently, if the header of the table is not empty, this now create the bug I've reported at https://github.com/sergiocorreia/panflute/issues/76#issuecomment-729833809
