### ISSUE TITLE
Table inside definition lists

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#9]
I suspect this is also an issue with [panflute](https://github.com/sergiocorreia/panflute).

```
Exercise +.#
  ~ Text

    |  | |
    | --- | --- | 
    | A | B |
```

when compiled with `pandoc MWE.md --filter pandoc-numbering -o MWE.pdf`, gives 

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 11, in <module>
    load_entry_point('pandoc-numbering==3.0.2', 'console_scripts', 'pandoc-numbering')()
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 693, in main
    return run_filters([numbering, referencing], prepare = prepare, doc = doc, finalize = finalize)
  File "/usr/local/lib/python2.7/dist-packages/panflute/io.py", line 246, in run_filters
    doc = doc.walk(action, doc)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 285, in walk
    altered = action(self, doc)
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 382, in numbering
    numbered = Numbered(elem, doc)
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 106, in __init__
    self._replace_marker()
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 137, in _replace_marker
    self._compute_data()
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 259, in _compute_data
    replace_description(self._elem, self._description)
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 299, in replace_description
    where.walk(partial(replacing, search='%D', replace=copy.deepcopy(description)))
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 274, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 272, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 269, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 282, in walk
    setattr(self, child, ans)
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 1161, in header
    self._header = TableRow(*value)
  File "/usr/local/lib/python2.7/dist-packages/panflute/elements.py", line 1078, in __init__
    self._set_content(args, TableCell)
  File "/usr/local/lib/python2.7/dist-packages/panflute/base.py", line 130, in _set_content
    self._content = ListContainer(*value, oktypes=oktypes, parent=self)
  File "/usr/local/lib/python2.7/dist-packages/panflute/containers.py", line 61, in __init__
    self.extend(args)  # self.oktypes must be set first
  File "/usr/lib/python2.7/_abcoll.py", line 675, in extend
    self.append(v)
  File "/usr/lib/python2.7/_abcoll.py", line 664, in append
    self.insert(len(self), value)
  File "/usr/local/lib/python2.7/dist-packages/panflute/containers.py", line 87, in insert
    v = check_type(v, self.oktypes)
  File "/usr/local/lib/python2.7/dist-packages/panflute/utils.py", line 29, in check_type
    raise TypeError(msg)
TypeError: received TableRow but expected <class 'panflute.elements.TableCell'>
Error running filter pandoc-numbering:
Filter returned error status 1
```

Replacing `Exercise +.#` with, e.g., `Text`, makes the error goes away.

**Comment by chdemko** [comment]
Yes, the same one
